apiVersion: v1
kind: Service
metadata:
  name: library-api-service
spec:
  selector:
    app: library-api # <--- This MUST match the label in your Deployment!
  ports:
    - protocol: TCP
      port: 80 # The port the SERVICE listens on
      targetPort: 5000 # The port the POD is listening on
  type: NodePort
